/*
 * Copyright 2017 ISE TU Berlin
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package de.tub.api;

import de.tub.model.Exams;
import org.joda.time.LocalDate;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2017-11-23T10:26:59.971Z")

@Api(value = "find", description = "the find API")
public interface FindApi {

    @ApiOperation(value = "", notes = "returns the last exams for a specific patient and test ", response = Exams.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = Exams.class),
        @ApiResponse(code = 404, message = "no data", response = Void.class) })
    
    @RequestMapping(value = "/find",
        method = RequestMethod.GET)
    ResponseEntity<Exams> findGet( @Min(0)@ApiParam(value = "minimal age") @RequestParam(value = "minage", required = false) Integer minage, @Min(0)@ApiParam(value = "maximal age ") @RequestParam(value = "maxage", required = false) Integer maxage,@ApiParam(value = "", allowableValues = "male, female") @RequestParam(value = "gender", required = false) String gender,@ApiParam(value = "name of the test to return", allowableValues = "cholesterol, triglyceride, hepatitis") @RequestParam(value = "type", required = false) String type,@ApiParam(value = "") @RequestParam(value = "startDate", required = false) LocalDate startDate,@ApiParam(value = "") @RequestParam(value = "endDate", required = false) LocalDate endDate);

}
