version: '3'
services:

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "0der1@b)Opd0Sis0nobxuS[uhId"
      MYSQL_DATABASE: "DITAS"

  cassandra:
    build:
      context: ./Cassandra/build
    links:
      - zipkin:zipkin

  elasticsearch:
    image: elasticsearch
    ports:
      - 9200:9200
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    command: "-Elogger.level=ERROR"

  vdc:
    build:
      context: ./vdc-nodered/
    links:
      - cassandra:cassandra
      - mysql:mysql
      - zipkin:zipkin
      - elasticsearch:elasticsearch
    volumes:
      - ./vdc/mnt:/var/log/mnt
    environment:
      - "elasticURI=elasticsearch:9200"
    depends_on:
      - cassandra
      - mysql
      - zipkin
      - elasticsearch
    ports:
      - 8080:8080

  dockbeat:
    build:
      context: ./dockbeat/
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  request-monitor:
    build:
      context: ./request-monitor/
    links:
      - vdc:vdc
      - elasticsearch:elasticsearch
      - zipkin:zipkin
    ports:
      - 8000:8000
    depends_on:
      - vdc
      - elasticsearch
      - zipkin
    environment:
      - "VDC_NAME=osrvdc"
      - "OPENTRACING=on"

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    environment:
      - JAVA_OPTS=-Dlogging.level.zipkin=DEBUG -Dlogging.level.zipkin2=DEBUG
      - "COLLECTOR_SAMPLE_RATE=1.0"
      - "STORAGE_TYPE=elasticsearch"
      - "ES_HOSTS=http://elasticsearch:9200"
    links:
      - elasticsearch:elasticsearch
