version: '3'
services:
  elasticserach:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    ports:
      - 9200:9200
    environment: 
      - "discovery.type=single-node"
  mysql:
    image: ditas/tub_example_mysql
    environment:
      MYSQL_ROOT_PASSWORD: "0der1@b)Opd0Sis0nobxuS[uhId"
      MYSQL_DATABASE: "DITAS"
    ports:
      - 3306:3306
  cassandra:
    image: ditas/tub_example_cassandra
    ports:
      - 9042:9042
      - 9160:9160
  vdc:
    build: 
      context: ./vdc-dummy/
    links:
       - cassandra:cassandra
       - mysql:mysql
    depends_on:
       - elasticserach
       - cassandra
       - mysql
    ports:
      - 8484:8484
      - 8080:8080
      - 8000:80
    volumes: 
      - .config:/.config/:ro
 