version: '3'
services:
  kcc:
    build:
      context: ./KeycloakSetup
      dockerfile: Dockerfile
    links:
     - keycloak:keycloak
    depends_on:
     - keycloak
  vdc:
    image: ditas/tub-mock-vdc
    ports:
      - "8888:8080"
    links:
     - dal:dal
    depends_on:
     - dal
    command: ["--dal","dal:8080"]
  dal:
    image: ditas/tub-mock-dal
  
  elasticsearch:
    build: ./elastic
    ports:
      - 9200:9200
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  keycloak:
    image: ditas/keycloak:production
    environment:
     - "KEYCLOAK_PASSWORD=UVhDKCuoQGMAMNAEBWH2gkU0JJR8DnXT"
    ports:
      - "4444:8080"
      - "4040:8443"
      - "4000:8000"
