version: '3'
services:
  kcc:
    build:
      context: ./KeycloakSetup
      dockerfile: Dockerfile
    links:
     - keycloak:keycloak
    depends_on:
     - keycloak
  vdc:
    image: ditas/tub-mock-vdc
    ports:
      - "8282:8080"
    links:
     - dal:dal
    depends_on:
     - dal
    command: ["--log","http://localhost:8484","--dal","dal:8080"]
  
  rm:
    image: ditas/vdc-request-monitor:production
    ports:
      - "8888:80"
      - "8884:443"
    volumes:
      - "./configs:/etc/ditas"
    links:
      - elasticsearch:elasticsearch
    pid: service:vdc
  
  log:
    image: ditas/vdc-logging-agent:production
    pid: service:vdc
    volumes:
      - "./configs:/etc/ditas"
    links:
      - elasticsearch:elasticsearch
  
  dal:
    image: ditas/tub-mock-dal
  
  elasticsearch:
    image: elasticsearch:5.6.15
    ports:
      - 9200:9200
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    command: "-Elogger.level=ERROR"
  keycloak:
    image: ditas/keycloak:production
    environment:
     - "KEYCLOAK_PASSWORD=UVhDKCuoQGMAMNAEBWH2gkU0JJR8DnXT"
    ports:
      - "4444:8080"
      - "4040:8443"
      - "4000:8000"

  client:
    build: ./client
    ports:
      - "3000:3000"
