version: '3'
services:
  mysql:
    image: mysql
    ports:
      - 6603:3306
    environment:
      MYSQL_ROOT_PASSWORD: "0der1@b)Opd0Sis0nobxuS[uhId"
      MYSQL_DATABASE: "DITAS"
    volumes:
      - ./MySQL/data/patient.sql:/docker-entrypoint-initdb.d/patient.sql
  cassandra:
    build:
      context: ./Cassandra/build
    ports:
      - 7000:7000
      - 7001:7001
      - 9042:9042
      - 9160:9160
    volumes:
      - ./Cassandra/data/exams.sql:/docker-entrypoint-initdb.d/exams.cql
  elasticsearch:
    image: elasticsearch
    ports:
      - 9200:9200
    environment: 
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  kibana:
    image: kibana
    ports:
      - 5601:5601
      - 5044:5044
  vdc:
    build:
      context: ./vdc/
    ports:
      - 8080:8080
    links:
      - cassandra:cassandra
      - mysql:mysql
      - elasticsearch:elasticsearch
    environment:
    - "elasticURI=elasticsearch:9200"
    
    depends_on:
      - cassandra
      - mysql
