version: '3'
services:
  mysql:
    image: mysql
    ports:
      - 6603:3306
    environment:
      MYSQL_ROOT_PASSWORD: "0der1@b)Opd0Sis0nobxuS[uhId"
      MYSQL_DATABASE: "DITAS"
    volumes:
      - ./MySQL/data/patient.sql:/docker-entrypoint-initdb.d/patient.sql
  cassandra:
    build:
      context: ./Cassandra/build
    ports:
      - 7000:7000
      - 7001:7001
      - 9042:9042
      - 9160:9160
    volumes:
      - ./Cassandra/data/exams.sql:/docker-entrypoint-initdb.d/exams.cql
  vdc:
    build:
      context: ./vdc/
    container_name: DITAS_OSR_VDC
    ports:
      - 8080:8080
    links: 
      - cassandra:cassandra
      - mysql:mysql
    depends_on: 
      - cassandra
      - mysql