version: '3'
services:

  mysql:
    image: ditas/tub_example_mysql
    environment:
      MYSQL_ROOT_PASSWORD: "0der1@b)Opd0Sis0nobxuS[uhId"
      MYSQL_DATABASE: "DITAS"

  cassandra:
    image: ditas/tub_example_cassandra

  vdc:
    build:
       context: ./vdc-dummy/
    links:
       - cassandra:cassandra
       - mysql:mysql
    depends_on:
       - cassandra
       - mysql
    ports:
      - 8484:8484
      - 8080:8080
      - 8000:8000
    environment:
      - "VDC_ADDRESS=localhost"
      - "VDC_PORT=8080"
      - "elasticURI=elasticsearch:9200" #Needes to be supllyed by the enviroment
      - "VDC_NAME=$VDC_NAME" #Needes to be supllyed by the enviroment
      - "OPENTRACING=off"
 