apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: vdc-config
spec:
  storageClassName: local
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/data/.config/"
  capacity:
    storage: 10Gi
status: {}
