swagger: '2.0'
info:
  description: ''
  version: 1.0.0
  title: OSR VDC
  termsOfService: 'http://swagger.io/terms/'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
schemes:
  - http
paths:
  '/patient/{SSN}':
    parameters:
      - name: SSN
        in: path
        description: unique ID of a patient
        required: true
        type: integer
        format: int32
    get:
      description: returns all the details of the patient
      summary: ''
      produces:
        - application/json
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Patient'
        '400':
          description: Invalid ID supplied
        '404':
          description: Patient not found
  '/exam/{SSN}':
    parameters:
      - name: SSN
        in: path
        description: unique ID of a patient
        required: true
        type: integer
        format: int32
    get:
      description: returns the last exams for a specific patient
      summary: ''
      parameters:
        - name: SSN
          in: path
          description: unique ID of a patient
          required: true
          type: integer
          format: int32
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Exams'
        '400':
          description: Invalid ID supplied
        '404':
          description: not exams found
  '/exam/{SSN}/{test}':
    parameters:
      - name: SSN
        in: path
        description: unique ID of a patient
        required: true
        type: integer
        format: int64
    get:
      description: 'returns the last exams for a specific patient and test '
      summary: ''
      parameters:
        - name: test
          in: path
          description: name of the test to return
          required: true
          type: string
          enum:
            - cholesterol
            - triglyceride
            - hepatitis
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Exams'
        '400':
          description: Invalid ID supplied
        '404':
          description: Patient not found
  /find:
    get:
      description: 'returns the last exams for a specific patient and test '
      summary: ''
      parameters:
        - name: minage
          in: query
          description: minimal age
          type: integer
          format: int32
          minimum: 0
        - name: maxage
          in: query
          description: 'maximal age '
          type: integer
          format: int32
          minimum: 0
        - name: gender
          in: query
          type: string
          enum:
            - male
            - female
        - name: type
          in: query
          description: name of the test to return
          type: string
          enum:
            - cholesterol
            - triglyceride
            - hepatitis
        - name: startDate
          in: query
          type: string
          format: date
        - name: endDate
          in: query
          type: string
          format: date
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Exams'
        '404':
          description: no data
definitions:
  Patient:
    properties:
      SSN:
        type: integer
        format: int32
      lastName:
        type: string
      name:
        type: string
      gender:
        type: string
        enum:
          - male
          - female
          - undefined
      mail:
        type: string
        format: email
      birthday:
        type: string
  Exam:
    properties:
      SSN:
        type: integer
        format: int32
      lastName:
        type: string
      name:
        type: string
      date:
        type: string
        format: date-time
      cholesterol:
        type: number
        format: double
      triglyceride:
        type: number
        format: double
      hepatitis:
        type: boolean
  Exams:
    type: array
    items:
      $ref: '#/definitions/Exam'
