swagger: '2.0'
info:
  description: 'swagger file for the example NodeRed Implementation of the VDC for the E-Health Use Case'
  version: 1.0.0
  title: OSR VDC - NodeRed
  termsOfService: 'http://swagger.io/terms/'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
schemes:
  - http
paths:
  '/patient/{SSN}':
    parameters:
      - name: SSN
        in: path
        description: unique ID of a patient
        required: true
        type: integer
        format: int32
    get:
      description: returns all the details of the patient
      summary: 'details can be {SSN, lastName, name, gender, mail, birthday}'
      produces:
        - application/json
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Patient'
        '400':
          description: Invalid ID supplied
        '404':
          description: Patient not found

definitions:
  Patient:
    properties:
      SSN:
        type: integer
        format: int32
      lastName:
        type: string
      name:
        type: string
      gender:
        type: string
        enum:
          - male
          - female
          - undefined
      mail:
        type: string
        format: email
      birthday:
        type: string