{
	"INTERNAL_STRUCTURE": {
		"Overview": {
			"name": "tub-mock-example",
			"description": "This is a vdc test example for integration testing of tub componentes",
			"tags": [
				{
					"method_id": "ask",
					"tags": []
				},
			]
		},
	"DATA_MANAGEMENT": [
		{
			"method_id": "ask",
			"attributes": {
				"dataUtility": [],
				"privacy": []
			}
		},
	],
	"ABSTRACT_PROPERTIES": [
		{
			"method_id": "ask",
			"goalTrees": {}
		},
	],
	"EXPOSED_API": {
  "openapi": "3.0.0",
  "info": {
    "description": "",
    "version": "1.0.0",
    "title": "CAF API",
    "termsOfService": "",
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    }
  },
  "tags": [],
  "paths": {
    "/ask": {
      "get": {
        "summary": "returns the answer to your question",
        "description": "",
        "parameters": [],
        "operationId": "ask",
        "responses": {
          "200": {
            "description": "Reply to a question nobody ever asked.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Reply"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Reply": {
        "type": "object",
        "properties": {
          "msg": {
            "type": "string"
          }
        }
      }
    }
  }
}
}
